backend:
  name: git-gateway
  branch: main

media_folder: "jingles"      # where Netlify CMS will upload files
public_folder: "/jingles"    # how they’ll be served

collections:

  # 1) CLIENTS
  - name: "clients"
    label: "Clients"
    folder: "data/clients"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "password",         label: "Password",         widget: "string" }
      - { name: "clientName",       label: "Client Name",      widget: "string" }
      - { name: "displayTitle",     label: "Display Title",    widget: "string" }
      - { name: "allowedPlaylists", label: "Allowed Playlists", widget: "list" }
      - { name: "ads",              label: "Ad Spots",         widget: "list" }

  # 2) PLAYLISTS
  - name: "playlists"
    label: "Playlists"
    folder: "playlists"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title",  label: "Title",  widget: "string" }
      - { name: "tracks", label: "Tracks", widget: "list" }

  # 3) BRAND JINGLES
  - name: "brand_jingles"
    label: "Brand Jingles"
    folder: "jingles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title",       widget: "string" }
      - { name: "file",  label: "Jingle File", widget: "file" }

  # 4) ADS
  - name: "ads"
    label: "Ad Spots"
    folder: "jingles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title",   widget: "string" }
      - { name: "file",  label: "Ad File", widget: "file" }