backend:
  name: git-gateway
  branch: main

media_folder: "jingles/{{media_folder}}"
public_folder: "/jingles/{{media_folder}}"

collections:

  # 1) CLIENTS
  - name:    "clients"
    label:   "Clients"
    folder:  "data/clients"
    create:  true
    slug:    "{{slug}}"
    summary: "{{displayTitle}}"

    fields:
      - { name: "password",       label: "Password",        widget: "string" }
      - { name: "clientName",     label: "Client Name",     widget: "string" }
      - { name: "displayTitle",   label: "Display Title",    widget: "string" }
      - { name: "allowedPlaylists", label: "Allowed Playlists", widget: "list" }
      - { name: "ads",            label: "Ad Spots",        widget: "list" }

  # 2) PLAYLISTS
  - name:    "playlists"
    label:   "Playlists"
    folder:  "playlists"
    create:  true
    slug:    "{{slug}}"
    summary: "{{slug}}"     # <-- prevents "missing title" error

    fields:
      - { name: "tracks", label: "Tracks", widget: "list" }

  # 3) BRAND JINGLES
  - name:    "brand_jingles"
    label:   "Brand Jingles"
    folder:  "jingles/{{media_folder}}/brand"
    create:  true
    slug:    "{{slug}}"
    summary: "{{clientName}} • {{playlist}}"

    fields:
      - { name: "clientName", label: "Client",   widget: "select", options: ["odiseja","bigbang"] }
      - { name: "playlist",   label: "Playlist", widget: "select", options: ["70s_POP","80s_POP","90s_POP","POP_ROCK","Easy80s90s","Movie_HITS","Movie_INSTRUMENTAL"] }
      - { name: "file",       label: "File",     widget: "file" }

  # 4) AD SPOTS
  - name:    "ads"
    label:   "Ad Spots"
    folder:  "jingles/{{media_folder}}/ads"
    create:  true
    slug:    "{{slug}}"
    summary: "{{slug}}"

    fields:
      - { name: "clientName", label: "Client", widget: "select", options: ["odiseja","bigbang"] }
      - { name: "file",       label: "File",   widget: "file" }